# Generated by Django 3.2.9 on 2021-11-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='course',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='university',
            new_name='designation',
        ),
    ]
