# Generated by Django 3.2.9 on 2021-11-27 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211127_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='rating',
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('item', models.CharField(max_length=128)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.skill')),
            ],
        ),
    ]
