# Generated by Django 3.2.9 on 2021-11-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211127_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='current_area',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='current_district',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='current_state',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
