# Generated by Django 3.2.9 on 2021-11-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
