# Generated by Django 3.2.9 on 2021-11-30 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_alter_project_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='categori',
        ),
    ]
